# theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
title: Jennifer Hawkin
logo: /images/Jenny.jpg
description: My personal webpage
aux_links:
  GitHub:
    - "https://github.com/hawkij"
  LinkedIn:
    - "https://www.linkedin.com/in/jennifer-hawkin/"
  ORCiD:
    - "https://orcid.org/0000-0001-6663-8494"

aux_links_new_tab: true
# url: https://hawkij.github.io/
nav_sort: case_insensitive
